[features.network_proxy]
enabled = true

[features.network_proxy.domains]
"172.30.0.1" = "allow"
"anthropic.com" = "allow"
"api.anthropic.com" = "allow"
"api.github.com" = "allow"
"api.npms.io" = "allow"
"api.openai.com" = "allow"
"api.snapcraft.io" = "allow"
"archive.ubuntu.com" = "allow"
"azure.archive.ubuntu.com" = "allow"
"bun.sh" = "allow"
"cdn.jsdelivr.net" = "allow"
"cdn.playwright.dev" = "allow"
"cdn.sheetjs.com" = "allow"
"chatgpt.com" = "allow"
"code.jquery.com" = "allow"
"codeload.github.com" = "allow"
"crl.geotrust.com" = "allow"
"crl.globalsign.com" = "allow"
"crl.identrust.com" = "allow"
"crl.sectigo.com" = "allow"
"crl.thawte.com" = "allow"
"crl.usertrust.com" = "allow"
"crl.verisign.com" = "allow"
"crl3.digicert.com" = "allow"
"crl4.digicert.com" = "allow"
"crls.ssl.com" = "allow"
"data.jsdelivr.com" = "allow"
"deb.nodesource.com" = "allow"
"deno.land" = "allow"
"docs.github.com" = "allow"
"esm.sh" = "allow"
"get.pnpm.io" = "allow"
"ghcr.io" = "allow"
"github-cloud.githubusercontent.com" = "allow"
"github-cloud.s3.amazonaws.com" = "allow"
"github.blog" = "allow"
"github.com" = "allow"
"github.githubassets.com" = "allow"
"*.githubusercontent.com" = "allow"
"googleapis.deno.dev" = "allow"
"googlechromelabs.github.io" = "allow"
"host.docker.internal" = "allow"
"json-schema.org" = "allow"
"json.schemastore.org" = "allow"
"jsr.io" = "allow"
"keyserver.ubuntu.com" = "allow"
"lfs.github.com" = "allow"
"nodejs.org" = "allow"
"npm.pkg.github.com" = "allow"
"npmjs.com" = "allow"
"npmjs.org" = "allow"
"objects.githubusercontent.com" = "allow"
"ocsp.digicert.com" = "allow"
"ocsp.geotrust.com" = "allow"
"ocsp.globalsign.com" = "allow"
"ocsp.identrust.com" = "allow"
"ocsp.sectigo.com" = "allow"
"ocsp.ssl.com" = "allow"
"ocsp.thawte.com" = "allow"
"ocsp.usertrust.com" = "allow"
"ocsp.verisign.com" = "allow"
"openai.com" = "allow"
"packagecloud.io" = "allow"
"packages.cloud.google.com" = "allow"
"packages.microsoft.com" = "allow"
"patch-diff.githubusercontent.com" = "allow"
"patchdiff.githubusercontent.com" = "allow"
"playwright.download.prss.microsoft.com" = "allow"
"ppa.launchpad.net" = "allow"
"raw.githubusercontent.com" = "allow"
"registry.bower.io" = "allow"
"registry.npmjs.com" = "allow"
"registry.npmjs.org" = "allow"
"registry.yarnpkg.com" = "allow"
"repo.yarnpkg.com" = "allow"
"s.symcb.com" = "allow"
"s.symcd.com" = "allow"
"security.ubuntu.com" = "allow"
"sentry.io" = "allow"
"skimdb.npmjs.com" = "allow"
"statsig.anthropic.com" = "allow"
"storage.googleapis.com" = "allow"
"telemetry.vercel.com" = "allow"
"ts-crl.ws.symantec.com" = "allow"
"ts-ocsp.ws.symantec.com" = "allow"
"www.googleapis.com" = "allow"
"www.npmjs.com" = "allow"
"www.npmjs.org" = "allow"
"yarnpkg.com" = "allow"
