[network]
allowed_domains = [
  "172.30.0.1",
  "anthropic.com",
  "api.anthropic.com",
  "api.github.com",
  "api.npms.io",
  "api.openai.com",
  "api.snapcraft.io",
  "archive.ubuntu.com",
  "azure.archive.ubuntu.com",
  "bun.sh",
  "cdn.jsdelivr.net",
  "cdn.playwright.dev",
  "cdn.sheetjs.com",
  "chatgpt.com",
  "code.jquery.com",
  "codeload.github.com",
  "crl.geotrust.com",
  "crl.globalsign.com",
  "crl.identrust.com",
  "crl.sectigo.com",
  "crl.thawte.com",
  "crl.usertrust.com",
  "crl.verisign.com",
  "crl3.digicert.com",
  "crl4.digicert.com",
  "crls.ssl.com",
  "data.jsdelivr.com",
  "deb.nodesource.com",
  "deno.land",
  "docs.github.com",
  "esm.sh",
  "get.pnpm.io",
  "ghcr.io",
  "github-cloud.githubusercontent.com",
  "github-cloud.s3.amazonaws.com",
  "github.blog",
  "github.com",
  "github.githubassets.com",
  "*.githubusercontent.com",
  "googleapis.deno.dev",
  "googlechromelabs.github.io",
  "host.docker.internal",
  "json-schema.org",
  "json.schemastore.org",
  "jsr.io",
  "keyserver.ubuntu.com",
  "lfs.github.com",
  "nodejs.org",
  "npm.pkg.github.com",
  "npmjs.com",
  "npmjs.org",
  "objects.githubusercontent.com",
  "ocsp.digicert.com",
  "ocsp.geotrust.com",
  "ocsp.globalsign.com",
  "ocsp.identrust.com",
  "ocsp.sectigo.com",
  "ocsp.ssl.com",
  "ocsp.thawte.com",
  "ocsp.usertrust.com",
  "ocsp.verisign.com",
  "openai.com",
  "packagecloud.io",
  "packages.cloud.google.com",
  "packages.microsoft.com",
  "patch-diff.githubusercontent.com",
  "patchdiff.githubusercontent.com",
  "playwright.download.prss.microsoft.com",
  "ppa.launchpad.net",
  "raw.githubusercontent.com",
  "registry.bower.io",
  "registry.npmjs.com",
  "registry.npmjs.org",
  "registry.yarnpkg.com",
  "repo.yarnpkg.com",
  "s.symcb.com",
  "s.symcd.com",
  "security.ubuntu.com",
  "sentry.io",
  "skimdb.npmjs.com",
  "statsig.anthropic.com",
  "storage.googleapis.com",
  "telemetry.vercel.com",
  "ts-crl.ws.symantec.com",
  "ts-ocsp.ws.symantec.com",
  "www.googleapis.com",
  "www.npmjs.com",
  "www.npmjs.org",
  "yarnpkg.com",
]
